import React, { useState, useEffect } from 'react';
import { FileText, AlertTriangle, ArrowRight, Loader2 } from 'lucide-react';
import hitlistData from '../hitlist_data.json';

const HitlistPanel = ({ onSelectProfile }) => {
  const [profiles, setProfiles] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    // In a real app fetching from backend, this would be an async call.
    // Here we import the static JSON generated by the python script.
    setProfiles(hitlistData);
    setLoading(false);
  }, []);

  if (loading) {
    return (
      <div className="flex items-center justify-center h-full text-stone-500">
        <Loader2 className="w-8 h-8 animate-spin mr-2" />
        <span>Loading Analysis...</span>
      </div>
    );
  }

  return (
    <div className="h-full overflow-y-auto bg-stone-50 p-6 font-serif">
      <div className="max-w-4xl mx-auto">
        <header className="mb-8 border-b border-stone-300 pb-4">
          <h1 className="text-3xl font-display text-stone-800 mb-2">Research Hitlist</h1>
          <p className="text-stone-600 italic">
            Top {profiles.length} profiles with conflicting data or missing information, analyzed by AI.
          </p>
        </header>

        <div className="space-y-6">
          {profiles.map((profile, index) => (
            <div
              key={profile.id}
              className="bg-white p-6 rounded shadow-sm border border-stone-200 relative group hover:shadow-md transition-shadow"
            >
              <div className="absolute top-4 right-4 text-stone-300 font-display text-4xl opacity-20 group-hover:opacity-40 select-none">
                #{index + 1}
              </div>

              <div className="flex items-start justify-between mb-4">
                <div>
                  <h2 className="text-xl font-bold text-stone-800 flex items-center gap-2">
                    {profile.name}
                    <span className="text-xs font-sans font-normal bg-stone-100 text-stone-500 px-2 py-1 rounded">
                      ID: {profile.id}
                    </span>
                  </h2>
                  <div className="text-sm text-stone-500 mt-1">
                    {profile.lineage} Lineage • {profile.generation}
                  </div>
                </div>
                {onSelectProfile && (
                  <button
                    onClick={() => onSelectProfile(profile.id)}
                    className="text-amber-700 hover:text-amber-900 flex items-center text-sm font-sans uppercase tracking-wider font-bold"
                  >
                    View Profile <ArrowRight className="w-4 h-4 ml-1" />
                  </button>
                )}
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">

                {/* Issues Column */}
                <div className="bg-rose-50 p-4 rounded border border-rose-100">
                  <h3 className="text-rose-800 font-bold text-sm uppercase tracking-wide mb-3 flex items-center">
                    <AlertTriangle className="w-4 h-4 mr-2" />
                    Detected Issues
                  </h3>
                  <ul className="list-disc list-inside space-y-1 text-sm text-rose-900">
                    {profile.issues.map((issue, i) => (
                      <li key={i}>{issue}</li>
                    ))}
                  </ul>
                  <div className="mt-4 text-xs text-rose-700 font-mono">
                    Conflict Score: {profile.score}
                  </div>
                </div>

                {/* Recommendations Column */}
                <div className="bg-indigo-50 p-4 rounded border border-indigo-100">
                  <h3 className="text-indigo-800 font-bold text-sm uppercase tracking-wide mb-3 flex items-center">
                    <FileText className="w-4 h-4 mr-2" />
                    AI Recommendations
                  </h3>
                  <ul className="space-y-2 text-sm text-indigo-900">
                    {profile.recommendations.map((rec, i) => (
                      <li key={i} className="flex items-start">
                        <span className="font-bold mr-2 text-indigo-400">{i+1}.</span>
                        <span>{rec}</span>
                      </li>
                    ))}
                  </ul>
                </div>

              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};

export default HitlistPanel;
